.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "STARDOG\-ADMIN_STORED_LIST" "8" "October 2017" "Stardog Union" "stardog-admin"
.
.SH "NAME"
\fBstardog\-admin_stored_list\fR \- Lists the queries currently stored in the system\.
.
.SH "SYNOPSIS"
\fBstardog\-admin\fR [ \-\-server \fIserver url\fR ] \fBstored\fR \fBlist\fR [ {\-p | \-\-passwd} \fIpassword\fR ] [ {\-P | \-\-ask\-password} ] [ {\-u | \-\-username} \fIusername\fR ] [ {\-v | \-\-verbose} ]
.
.SH "OPTIONS"
.
.TP
\fB\-p\fR \fIpassword\fR, \fB\-\-passwd\fR \fIpassword\fR
Password\.
.
.TP
\fB\-P\fR, \fB\-\-ask\-password\fR
Prompt for password\.
.
.TP
\fB\-\-server\fR \fIserver url\fR
URL of Stardog Server\. If this option isn\'t specified, it will be read from JVM argument \'stardog\.default\.cli\.server\'\. If the JVM arg isn\'t set, the default value \'http://localhost:5820\' is used\. If server URL has no explicit port value, the default port value \'5820\' is used\. Example: \'stardog\-admin \-\-server http://12\.34\.56\.78:5820 server stop\'
.
.TP
\fB\-u\fR \fIusername\fR, \fB\-\-username\fR \fIusername\fR
User name\.
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Verbose flag that causes more detailed information to be printed
.
.SH "EXAMPLES"
.
.TP
Lists the names and query strings of all stored queries:
$ stardog\-admin stored list
.
.TP
Lists all stored queries with more details:
$ stardog\-admin stored list \-\-verbose

