.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "STARDOG\-ADMIN_VIRTUAL_IMPORT" "8" "October 2017" "Stardog Union" "stardog-admin"
.
.SH "NAME"
\fBstardog\-admin_virtual_import\fR \- Registers a new virtual graph\.
.
.SH "SYNOPSIS"
\fBstardog\-admin\fR \fBvirtual\fR \fBimport\fR [ {\-f | \-\-format} \fIMappings format\fR ] [ {\-g | \-\-named\-graph} \fInamed graph\fR ] [ {\-p | \-\-passwd} \fIpassword\fR ] [ {\-P | \-\-ask\-password} ] [ \-\-remove\-all ] [ {\-u | \-\-username} \fIusername\fR ] [ {\-v | \-\-verbose} ] [\-\-] \fIdatabase name\fR \fIconfigFile\fR \fImappingsFile\fR \fIinputFile\fR\.\.\.
.
.SH "OPTIONS"
.
.TP
\fB\-f\fR \fIMappings format\fR, \fB\-\-format\fR \fIMappings format\fR
Format of the mappings; one of [STARDOG, R2RML]
.
.TP
\fB\-g\fR \fInamed graph\fR, \fB\-\-named\-graph\fR \fInamed graph\fR
Target named graph\. If no named graph is specified, the default graph will be used\. This is the named graph where data will be imported into\.
.
.TP
\fB\-p\fR \fIpassword\fR, \fB\-\-passwd\fR \fIpassword\fR
Password\.
.
.TP
\fB\-P\fR, \fB\-\-ask\-password\fR
Prompt for password\.
.
.TP
\fB\-\-remove\-all\fR
Remove all flag\. If this flag is set, all data in destination named graph will be removed before the import\.
.
.TP
\fB\-u\fR \fIusername\fR, \fB\-\-username\fR \fIusername\fR
User name\.
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Verbose flag that causes more detailed information to be printed
.
.TP
\-\-
This option can be used to separate command\-line options from the list of arguments (useful when arguments might be mistaken for command\-line options)\.
.
.TP
\fIdatabase name\fR \fIconfigFile\fR \fImappingsFile\fR \fIinputFile\fR
The name of the database to import the data followed by a configuration file, a mappings file and an inputfile\. When importing from an RDBMS the configuration file is required, the mappings file is optional (when absent direct mapping is used), and input file argument is not used\. When importing CSV, the configuration file is optional, the mappings file and the input file (should be a valid CSV file) are required\.
.
.SH "EXAMPLES"
.
.TP
Import all of the contents of a virtual graph with direct mappings into database myDB
$ stardog\-admin virtual import myDB source\.properties
.
.TP
Import all of the contents of a virtual graph with the mappings written in Stardog mappings syntax
$ stardog\-admin virtual import myDB source\.properties source\.ttl
.
.TP
Import all of the contents of a virtual graph with the mappings written in standard R2RML Turtle syntax
$ stardog\-admin virtual import \-\-format r2rml myDB source\.properties source\.ttl
.
.TP
Import the contents of a CSV file with the given mappings
$ stardog\-admin virtual import myDB mappings\.ttl input\.csv

