.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "STARDOG\-ADMIN_STORED_ADD" "8" "October 2017" "Stardog Union" "stardog-admin"
.
.SH "NAME"
\fBstardog\-admin_stored_add\fR \- Adds a new stored query
.
.SH "SYNOPSIS"
\fBstardog\-admin\fR [ \-\-server \fIserver url\fR ] \fBstored\fR \fBadd\fR [ {\-d | \-\-database} \fIdb\fR ] [ {\-n | \-\-name} \fIname\fR ] [ \-\-overwrite ] [ {\-p | \-\-passwd} \fIpassword\fR ] [ {\-P | \-\-ask\-password} ] [ \-\-shared ] [ {\-u | \-\-username} \fIusername\fR ] [ {\-v | \-\-verbose} ] [\-\-] \fIquery\fR
.
.SH "OPTIONS"
.
.TP
\fB\-d\fR \fIdb\fR, \fB\-\-database\fR \fIdb\fR
The database the query will be associated with\. By default, \'*\' willbe used which means the query can be executed over any database\.
.
.TP
\fB\-n\fR \fIname\fR, \fB\-\-name\fR \fIname\fR
Unique name for the stored query\. This name is used to retrieve the stored query later\. If no name is given but a query file is provided the name of the file without the extension will be used\. The first letter must be an alpha character\. Subsequent characters may be alphanumeric, underscore, or dash\.
.
.TP
\fB\-\-overwrite\fR
Overwrite an existing stored query with the same name\.
.
.TP
\fB\-p\fR \fIpassword\fR, \fB\-\-passwd\fR \fIpassword\fR
Password\.
.
.TP
\fB\-P\fR, \fB\-\-ask\-password\fR
Prompt for password\.
.
.TP
\fB\-\-server\fR \fIserver url\fR
URL of Stardog Server\. If this option isn\'t specified, it will be read from JVM argument \'stardog\.default\.cli\.server\'\. If the JVM arg isn\'t set, the default value \'http://localhost:5820\' is used\. If server URL has no explicit port value, the default port value \'5820\' is used\. Example: \'stardog\-admin \-\-server http://12\.34\.56\.78:5820 server stop\'
.
.TP
\fB\-\-shared\fR
Share this query with other users\. By default, only the user who stores the query can access it\.
.
.TP
\fB\-u\fR \fIusername\fR, \fB\-\-username\fR \fIusername\fR
User name\.
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Verbose flag that causes more detailed information to be printed
.
.TP
\-\-
This option can be used to separate command\-line options from the list of arguments (useful when arguments might be mistaken for command\-line options)\.
.
.TP
\fIquery\fR
The SPARQL query string to store\. This can either be a file name or a SPARQL query string\.
.
.SH "DISCUSSION"
Adds a new stored query\. Stored queries can be executed directly by using their name\. Shared queries can be executed by any user\. Private queries can only be executed by their creator or super users\. Stored queries can be executed over the database associated with the query\. The special value \fB*\fR can be used to indicate a query can be executed over any database\.
.
.SH "EXAMPLES"
.
.TP
Adds a new stored query over all databases:
$ stardog\-admin stored add listProperties\.sparql
.
.TP
Adds a new shared stored query with a custom name and for database myDb:
$ stardog\-admin stored add \-\-shared \-d myDb \-n listProperties query\.sparql
.
.TP
Adds a new stored query overwriting previous query with same name:
$ stardog\-admin stored add \-\-overwrite \-d myDb \-n listProperties query\.sparql

