.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "STARDOG_NAMESPACE_EXPORT" "1" "October 2017" "Stardog Union" "stardog"
.
.SH "NAME"
\fBstardog_namespace_export\fR \- Exports the namespace prefixes stored in a database in Turtle or SPARQL format\.
.
.SH "SYNOPSIS"
\fBstardog\fR \fBnamespace\fR \fBexport\fR [ {\-p | \-\-passwd} \fIpassword\fR ] [ {\-P | \-\-ask\-password} ] [ \-\-sparql ] [ {\-u | \-\-username} \fIusername\fR ] [ {\-v | \-\-verbose} ] [\-\-] \fIdatabase\fR \fIfile\fR\.\.\.
.
.SH "OPTIONS"
.
.TP
\fB\-p\fR \fIpassword\fR, \fB\-\-passwd\fR \fIpassword\fR
Password\.
.
.TP
\fB\-P\fR, \fB\-\-ask\-password\fR
Prompt for password\.
.
.TP
\fB\-\-sparql\fR
Flag to use SPARQL format for namespaces, i\.e\. print \'PREFIX\' instead of \'@prefix\' and no period at the end\.
.
.TP
\fB\-u\fR \fIusername\fR, \fB\-\-username\fR \fIusername\fR
User name\.
.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Verbose flag that causes more detailed information to be printed
.
.TP
\-\-
This option can be used to separate command\-line options from the list of arguments (useful when arguments might be mistaken for command\-line options)\.
.
.TP
\fIdatabase\fR \fIfile\fR
The name of the database or the full connection string of the database to connect to\. If only the name is provided, the default server URL will be pre\-pended to the name of the database in order to construct the connection string\. Connection parameters such as \';reasoning=true\' can be included in the provided database name\. Connection parameters specified like this can be overridden by specific options on the command\. The default server URL will be read from the JVM argument \'stardog\.default\.cli\.server\'\. If the JVM argument is not set, the default value \'http://localhost:5820\' is used\. If the server URL has no explicit port value, the default port value \'5820\' is used\. To use a secure connection, you should specify the full connection string and postfix \'s\' to the protocol, e\.g\. https\. The subsequent argument is the output file\.
.
.SH "EXAMPLES"
.
.TP
Exports the namespaces of \'myDb\' in Turtle format:
$ stardog namespace export myDb
.
.TP
Exports the namespaces of \'myDb\' in SPARQL format:
$ stardog namespace export \-\-sparql myDb
.
.TP
Exports the namespaces of \'myDb\' in Turtle format to a specified file:
$ stardog namespace export myDb ns\.ttl

